-- AlterTable
ALTER TABLE "Pet" ADD COLUMN     "rarity" TEXT NOT NULL DEFAULT 'COMMON',
ADD COLUMN     "species" TEXT NOT NULL DEFAULT 'Chicken',
ADD COLUMN     "type" TEXT NOT NULL DEFAULT 'ANIMAL';
